### ISSUE TITLE
v3 The next steps

### ISSUE THREAD

**Issue by JMSwag** [Digital-Sapphire/PyUpdater#87]
# ToDo

### CI/CD Support

Please see #36 

##### PyUpdater as a whole
- [ ] Overall refactoring of class APIs
- [ ] Change asymmetric key type. See #45 for more info.

##### Client

 - [ ] Add support for version manifest per platform.

##### KeyHandler
- [ ] Allow reading private key from env var

#### PackageHandler
- [ ] Create individual manifests for each platform
- [ ] Download latest manifest from online repository

**Comment by marcelomanzo** [comment]
This is great. I really appreciate the re-factoring of the key type.
I'm planning to ship my app within I month, any idea how long it will take the fix? (I could use the dev channel)
I really liked the way that you implemented the auto update mechanism and I want to leverage that.

**Comment by marcelomanzo** [comment]
I can also help with CI and CD, I'm using Gitlab for this project right now.

**Comment by JMSwag** [comment]
@marcelomanzo I can not give a date at the moment. The apps will update the same in the same manner. Only the way the client looks for version manifest will change.

**Comment by wettenhj** [comment]
Hi @JMSwag,

I thought I'd chime in to let you know that I'm still very interested in this project, but I haven't fully implemented the auto-updating workflow in our PyInstaller-built application yet for various reasons.

As a temporary stop-gap, I implemented something simpler - just new version alerts without the ability to auto-update.

I thought it might be worth describing how I do the new version alerts to see if it could fit into a future PyUpdater workflow.  We use GitHub Releases and its RESTful API to check for new versions.  I'm not sure if there's a standard example GitHub repository people use for illustrating points like this, but I'll just pick a popular repository which uses GitHub Releases - https://github.com/twbs/bootstrap

I use the following 3 API endpoints:

1. https://api.github.com/repos/twbs/bootstrap/releases/latest
- This gives the latest stable (non-beta) release.
- Fields of interest within the JSON response are:
  - tag_name
  - body (Describes new features in this release)
  - published_at (date / time)
  - assets (JSON list of release assets, which can include binary downloads for different OS's)

2. https://api.github.com/repos/twbs/bootstrap/releases
- This gives the latest 20 releases with the most recent at the top (which could be a beta release).
- In addition to the "Fields of interest" listed above, this one is now relevant:
  - prerelease (true for an alpha or beta)

3. https://api.github.com/repos/twbs/bootstrap/git/refs/tags/v4.0.0-beta
- This gives the SHA hash of a particular release / tag

Now when comparing the version we are currently running with the latest version from the GitHub Releases API, I do this slightly differently depending on whether we are using an unofficial local commit (SHA not yet pushed to GitHub), in which case I can use "git log -1 --pretty=format:%ci" to determine its date/time, or if the SHA is available on GitHub in an official release, then I can use the GitHub Releases API to get its "published_at" date/time.

GitHub API queries are throttled, so I cache the results in a local JSON or Pickle file.

Does this sound like something which could fit into PyUpdater's workflow?  My biggest question is whether release assets (binaries) are expected to be in the root directory of the URL you supply to PyUpdater, or whether the download URL can be determined by a RESTful API call?

**Comment by JMSwag** [comment]
Hey @wettenhj,

Thanks for your input. I'm not able to distill exactly what's being asked here. Are you looking for a way to alert your users when there is an update available?

Release assets are required to be in the root directory.

**Comment by wettenhj** [comment]
Hi @JMSwag, sorry for the lack of clarity.

Would you see any value in allowing release assets to be in release-specific subdirectories of the base URL like "latest/" or "v1.0.5/" if I were to submit a Pull Request?

Currently .pyupdater/config.pyu can refer to a Python module (client_config.py), but UPDATE_URLS must be pre-configured.  I would like to make it possible to configure the URL(s) dynamically from a Python module, e.g. get_update_url.py.  The pre-configured UPDATE_URLS method should still work for backwards compatibility, but I'd like a way to overwrite it dynamically.

The download URL / subdirectory could be determined dynamically like this:

1. Ask the Releases API (e.g. GitHub Releases) for an appropriate version to upgrade to based on whether we're currently running an alpha, beta or stable, and retrieve the asset download URL (i.e. subdirectory within the base URL) for that version.
2. Download versions.gz etc. from the asset download URL for that version and determine whether we can upgrade with a patch etc.

Obviously not everyone would be using GitHub Releases, so the default get_update_url.py could simply return the URLs already in the pre-configured UPDATE_URLS setting.

**Comment by JMSwag** [comment]
@moscoquera Suggestions here are welcome.

**Comment by wolfamongus2** [comment]
Suggestions for v3 [officially] is bitbucket integration as its free and has good bandwidth with no overhead.  There are others - google drive, github but this is free and has private repos which would help minimise spam.  Amazon s3 for example is easy to spam and will cost you a fortune.

**Comment by moscoquera** [comment]
from the conversation with @TysonDogerz and issue #104, i would like to suggest this features for v3:

- Bundle app_version automatically in the built app: this's can be very useful avoiding behaviors like constant updating due a bad configuration (easy mistake to made).
- Add a plugin like structure (static languages call it: interfaces :smile: ) to allow updates from diverse kind of services (web servers, Github, BitBucker, GoogleDrive, S3, FTP, etc..)
- FTP upload plugin.

**Comment by jwaschkau** [comment]
@JMSwag Maybe it is interesting to integrate tuf to get better update security:
https://github.com/theupdateframework/tuf

**Comment by jytinjalmon** [comment]
I like the bit bucket idea and private repositories.   I am wanting to ship an application this year and I can see the value in a free solution.  You worry less if clients spam your server.

**Comment by moscoquera** [comment]
hi again.
@JMSwag what do you think about the refactor to the download client? to support ftp, http, bitbucket.. etc... downloads. i have a more free time now and can start coding it.

**Comment by moscoquera** [comment]
does tuf solve the issue with the key generation on windows x64 python?

**Comment by JMSwag** [comment]
@moscoquera I really like that idea! I'd love to see what you can come up with.

**Comment by JMSwag** [comment]
@jwaschkau This project was originally called Not-So-Tuf. When I originally looked at TUF a few years ago, it required more setup than what I was ready to invest at the time. If an end user is in need of more security I would recommend TUF.

**Comment by flutefreak7** [comment]
I'd like to see the core updater product be the focus, rather than the ability to interface with lots of various upload and download services.  I'm using this behind corporate firewall and just hosting the files on a webserver I run or on a network share or whatever.  I think solving the problem of making the updates available over the internet is a larger separate problem from the core problem that PyUpdater solves.  Just thought I'd throw that out there to try and focus the scope a little.

**Comment by JMSwag** [comment]
Hi all. With my time as limited as it is, I cannot support the effort to change PyUpdater drastically. Going forward I'd like to keep PyUpdater as simple as it is. Some of the things I'd like to accomplish, in the near future, are as follows.

- Support all Python version that pyinstaller supports
- Fix/Add arm support

Thoughts?

**Comment by JMSwag** [comment]
Hey Everyone, I'm implementing the work for CI/CD support and have a question in #188. Please join with your input.

**Comment by JMSwag** [comment]
Support for downloading from services like Github Releases, Bitbucket & Bintray has been added in #195.
